#http
GET  http://localhost:3000/api/admin_member HTTP/1.1

###
POST  http://localhost:3000/api/admin_member HTTP/1.1
content-type: application/json

{
  "user": {
    "firstName": "Martin",
    "lastName": "Braun",
    "email": "martin.braun@schoolmehome.com"
  }
}